auto: true
permalink: /:year/:month/:day/:title
pygments: true
paginate: 8
exclude:
  - CNAME
  - Makefile
  - README.md
adsense_publisher_id: pub-9368826237916342
analytics_account: UA-27505414-1
chrome_extensions:
  - dcjnfaoifoefmnbhhlbppaebgnccfddf
  - kflemogpkbophbipihnbcmlplbihbdhb
  - gbgogigdaibinioohdhejplmajgkkfdn
me:
  cloud9: http://c9.io/neocotic
  email: mercer.alasdair@gmail.com
  facebook: http://www.facebook.com/alasdair.mercer
  github: https://github.com/neocotic
  google: https://plus.google.com/114861910136746455630
  gravatar: http://www.gravatar.com/avatar/2471461cd50e090859ce5291760f3594
  home: http://neocotic.com
  linkedin: http://www.linkedin.com/profile/view?id=71374926
  psn: http://us.playstation.com/publictrophy/index.htm?onlinename=Apehawk
  scrim: http://scr.im/neocotic
  steam: http://steamcommunity.com/id/neocotic/
  twitter: https://twitter.com/neocotic
  xbox: http://live.xbox.com/en-US/Profile?gamertag=neocotic
origin: http://neocotic.com
project:
  blingaer: &blingaer
    name: blingaer
    title: blingaer
  blingier: &blingier
    name: blingier
    title: blingier
  cssutils: &cssutils
    name: css-utils
    title: css-utils
    version: "1.0.0"
  dateext: &dateext
    name: date-ext
    title: date-ext
    version: "1.0.2"
  gitant: &gitant
    name: git-ant
    title: git-ant
  gitpress: &gitpress
    name: GitPress
    title: GitPress
  htmlmd: &htmlmd
    name: html.md
    title: html.md
    version: "1.0.0"
  iorder: &iorder
    name: iOrder
    title: iOrder
    version: "1.1.2"
  jqueryconsole: &jqueryconsole
    name: jquery-console
    title: jQuery Console
  jqueryjsonx: &jqueryjsonx
    name: jquery-jsonx
    title: jQuery JSONX
    version: "1.0.0"
  jsonpjs: &jsonpjs
    name: jsonp.js
    title: jsonp.js
    version: "1.0.0"
  jsonx: &jsonx
    name: jsonx
    title: JSONX
    version: "1.0.0"
  mediad: &mediad
    name: mediad
    title: mediad
  morjs: &morjs
    name: mor.js
    title: mor.js
    version: "1.0.2"
  pathlength: &pathlength
    name: pathlength
    title: pathlength
  phonyjs: &phonyjs
    name: phony.js
    title: Phony
    version: "1.0.1"
  qrjs: &qrjs
    name: qr.js
    title: qr.js
    version: "1.0.3"
  template: &template
    created: 2011-03-29
    name: template
    title: Template
    updated: 2012-05-31
    version: "1.1.4"
  undowikipediablackout: &undowikipediablackout
    name: UndoWikipediaBlackout
    title: Undo Wikipedia Blackout
    version: "1.2.1"
  yourlsapi: &yourlsapi
    name: yourls-api
    title: yourls-api
    version: "1.0.0"
projects:
  - *blingaer
  - *blingier
  - *cssutils
  - *dateext
  - *gitant
  - *gitpress
  - *htmlmd
  - *iorder
  - *jqueryconsole
  - *jqueryjsonx
  - *jsonpjs
  - *jsonx
  - *mediad
  - *morjs
  - *pathlength
  - *phonyjs
  - *qrjs
  - *template
  - *undowikipediablackout
  - *yourlsapi