auto: true
permalink: /:year/:month/:day/:title
pygments: true
paginate: 5
exclude:
- CNAME
- Makefile
- README.md
chrome_extensions:
- dcjnfaoifoefmnbhhlbppaebgnccfddf
- kflemogpkbophbipihnbcmlplbihbdhb
- gbgogigdaibinioohdhejplmajgkkfdn
projects:
- blingaer
- blingier
- css-utils
- date-ext
- git-ant
- GitPress
- html.md
- iOrder
- jquery-console
- jquery-jsonx
- jsonp.js
- jsonx
- mediad
- mor.js
- phony.js
- qr.js
- template
- UndoWikipediaBlackout
- yourls-api